language: python
python:
  - '3.5'
notifications:
  email: never
before_script:
  - pip install coverage
  - pip install termcolor
script: 
  - coverage run --source setup.py rpn_test.py
after_success: coveralls
